version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      development-dependencies:
        dependency-type: development
    labels: [dependencies, out-of-stream]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, out-of-stream]
