# ============================================================================
# metadata:
#   status: inactive
#   implemented: false
#   automation: none
#   spec: docs/60-practice-operations/01-quality-improvement-and-accreditation.md
#   standards: [C3.1, QI1.1, QI2.1, GP3.1]
#   domain: practice-operations
#   last_reviewed: 2026-08-25
# ============================================================================
@inactive @not-implemented @practice-operations @compliance
Feature: Accreditation evidence
  As a practice manager
  I want evidence to accumulate as a by-product of normal work
  So that accreditation is not a three-yearly scramble

  Scenario: Every criterion is a tracked row
    When I open the accreditation register
    Then every RACGP Standards criterion from C1.1 to GP6.1 is listed
    And each shows a status, evidence, an owner and a review date

  Scenario Outline: System-generated evidence is attached automatically
    Given the criterion "<criterion>"
    Then "<evidence>" is generated by the system and attached

    Examples:
      | criterion | evidence                                     |
      | C6.3      | audit log access reports                     |
      | C7.1      | note completeness metrics                    |
      | QI2.1     | health summary completeness percentage       |
      | QI2.2     | medication reconciliation and allergy recording rates |
      | GP2.2     | recall closure rates and outstanding results ageing |
      | GP3.1     | credential register with expiry status       |
      | GP4.1     | sterilisation logs                           |
      | GP6.1     | cold chain temperature records and breach handling |

  Scenario: Evidence is dated and reproducible
    When system-generated evidence is attached
    Then it carries the date it was generated
    And it can be regenerated for the same period

  Scenario: The accreditation cycle produces a preparation plan
    Given the certificate expires in 6 months
    Then a preparation plan is generated listing outstanding criteria

  Scenario: A mock assessment produces the full evidence pack
    When I run a mock assessment
    Then a complete evidence pack is produced for every criterion
