# ============================================================================
# metadata:
#   status: inactive
#   implemented: true
#   automation: none
#   spec: docs/10-practice-setup/06-fee-schedules-and-billing-setup.md
#   standards: [C1.5, C3.1]
#   domain: practice-setup
#   last_reviewed: 2026-08-25
# ============================================================================
@inactive @not-implemented @practice-setup @medicare
Feature: Fee schedules
  As a practice manager
  I want fee schedules per payer
  So that every service is priced correctly and the patient gap is visible

  Background:
    Given I am signed in as the practice manager of "Brunswick Family Practice"

  Scenario: Schedules are seeded during onboarding
    When billing setup completes
    Then the following fee schedules exist:
      | name            | basis                          | editable |
      | Bulk Bill (MBS) | 100% of the MBS benefit        | false    |
      | Private         | MBS schedule fee × multiplier  | true     |
      | DVA             | DVA schedule                   | false    |
      | WorkCover       | State WorkCover schedule       | true     |
      | Non-Medicare    | Practice defined               | true     |

  @compliance
  Scenario: The bulk bill schedule cannot be edited
    When I try to change the fee for item "23" on the "Bulk Bill (MBS)" schedule
    Then the change is refused
    And I am told this schedule is fixed to the Medicare benefit

  Scenario: The private schedule is generated by a multiplier and rounding
    Given the practice multiplier is 1.75 and rounding is to the nearest $5
    When the private schedule is generated
    Then each item's fee is the MBS schedule fee multiplied and rounded
    And each item shows the resulting patient gap

  @compliance
  Scenario: The patient gap is shown alongside every private fee
    When I view the "Private" schedule
    Then each row shows the schedule fee, the Medicare benefit and the gap
    And the gap is the most prominent figure

  Scenario: Repricing does not change invoices already raised
    Given an invoice was raised on "2026-06-01" for item "23" at $95.00
    When the private schedule fee for item "23" changes to $105.00
    Then the existing invoice still shows $95.00
    And new invoices use $105.00
