import { Inject, Injectable } from '@nestjs/common';
import { eq } from 'drizzle-orm';
import {
  APPOINTMENT_TYPE_SEED,
  FEE_SCHEDULE_LABELS,
  LOCKED_FEE_SCHEDULE_KINDS,
  NON_MEDICARE_ITEM_SEED,
  TRIAGE_PROMPT_SEED,
  type FeeScheduleKind,
} from '@gp/contracts';
import { DATABASE } from '../../db/database.module';
import type { Database } from '../../db/client';
import {
  appointmentTypes,
  feeScheduleItems,
  feeSchedules,
  mbsItems,
  triagePrompts,
} from '../../db/schema';
import { uuidv7 } from '../../db/uuid';

/**
 * Seeds a newly created practice with the defaults an Australian general practice
 * would otherwise have to type in from scratch: appointment types, the four payer
 * fee schedules, and the red-flag triage prompt set.
 */
@Injectable()
export class PracticeSeedService {
  constructor(@Inject(DATABASE) private readonly db: Database) {}

  async seedPractice(practiceId: string): Promise<void> {
    await Promise.all([
      this.seedAppointmentTypes(practiceId),
      this.seedTriagePrompts(practiceId),
    ]);
    // Fee schedules depend on the MBS catalogue, so they run after it is present.
    await this.seedFeeSchedules(practiceId);
  }

  private async seedAppointmentTypes(practiceId: string): Promise<void> {
    await this.db.insert(appointmentTypes).values(
      APPOINTMENT_TYPE_SEED.map((seed, index) => ({
        id: uuidv7(),
        practiceId,
        name: seed.name,
        shortCode: seed.shortCode,
        durationMinutes: seed.durationMinutes,
        colour: seed.colour,
        description: seed.description,
        allowedPractitionerKinds: seed.allowedPractitionerKinds as string[],
        onlineBookable: seed.onlineBookable,
        requiresTriagePrompt: seed.requiresTriagePrompt ?? false,
        defaultMbsItemNumber: seed.defaultMbsItem,
        sortOrder: index,
      })),
    );
  }

  private async seedTriagePrompts(practiceId: string): Promise<void> {
    await this.db.insert(triagePrompts).values(
      TRIAGE_PROMPT_SEED.map((seed) => ({
        id: uuidv7(),
        practiceId,
        promptKey: seed.key,
        label: seed.label,
        matches: seed.matches,
        question: seed.question,
        action: seed.action,
        blocksOnlineBooking: seed.blocksOnlineBooking,
      })),
    );
  }

  /**
   * Creates the five schedules. Bulk Bill is locked to the MBS benefit; Private is
   * generated by multiplier so the practice can see the gap immediately.
   */
  private async seedFeeSchedules(
    practiceId: string,
    multiplierBp = 17500,
    roundingCents = 500,
  ): Promise<void> {
    const catalogue = await this.db.select().from(mbsItems);
    const today = new Date().toISOString().slice(0, 10);
    const kinds: FeeScheduleKind[] = ['bulk_bill', 'private', 'dva', 'workcover', 'non_medicare'];

    for (const kind of kinds) {
      const [schedule] = await this.db
        .insert(feeSchedules)
        .values({
          id: uuidv7(),
          practiceId,
          kind,
          name: FEE_SCHEDULE_LABELS[kind],
          isEditable: !LOCKED_FEE_SCHEDULE_KINDS.includes(kind),
          isDefault: kind === 'bulk_bill',
          effectiveFrom: today,
        })
        .returning();

      if (kind === 'non_medicare') {
        await this.db.insert(feeScheduleItems).values(
          NON_MEDICARE_ITEM_SEED.map((item) => ({
            id: uuidv7(),
            practiceId,
            feeScheduleId: schedule.id,
            itemCode: item.code,
            description: item.description,
            feeCents: item.defaultFeeCents,
            benefitCents: 0,
            effectiveFrom: today,
          })),
        );
        continue;
      }

      if (!catalogue.length) continue;

      await this.db.insert(feeScheduleItems).values(
        catalogue.map((item) => {
          const benefit = Math.round((item.scheduleFeeCents * item.benefitPercent) / 100);
          const fee =
            kind === 'private'
              ? roundTo((item.scheduleFeeCents * multiplierBp) / 10000, roundingCents)
              : benefit;
          return {
            id: uuidv7(),
            practiceId,
            feeScheduleId: schedule.id,
            mbsItemId: item.id,
            itemCode: item.itemNumber,
            description: item.description,
            feeCents: fee,
            benefitCents: benefit,
            effectiveFrom: today,
          };
        }),
      );
    }
  }

  /** Regenerate the private schedule after the practice changes its multiplier. */
  async regeneratePrivateSchedule(
    practiceId: string,
    multiplierBp: number,
    roundingCents: number,
  ): Promise<void> {
    const [schedule] = await this.db
      .select()
      .from(feeSchedules)
      .where(eq(feeSchedules.practiceId, practiceId))
      .then((rows) => rows.filter((r) => r.kind === 'private'));
    if (!schedule) return;

    const catalogue = await this.db.select().from(mbsItems);
    const today = new Date().toISOString().slice(0, 10);

    await this.db.delete(feeScheduleItems).where(eq(feeScheduleItems.feeScheduleId, schedule.id));
    if (!catalogue.length) return;

    await this.db.insert(feeScheduleItems).values(
      catalogue.map((item) => {
        const benefit = Math.round((item.scheduleFeeCents * item.benefitPercent) / 100);
        return {
          id: uuidv7(),
          practiceId,
          feeScheduleId: schedule.id,
          mbsItemId: item.id,
          itemCode: item.itemNumber,
          description: item.description,
          feeCents: roundTo((item.scheduleFeeCents * multiplierBp) / 10000, roundingCents),
          benefitCents: benefit,
          effectiveFrom: today,
        };
      }),
    );
  }
}

function roundTo(cents: number, nearest: number): number {
  if (nearest <= 0) return Math.round(cents);
  return Math.round(cents / nearest) * nearest;
}
